"""T3.1 features status columns

Revision ID: 48172b100cdf
Revises: 842a42f73f0f
Create Date: 2026-05-06 10:01:18.439367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48172b100cdf'
down_revision: Union[str, Sequence[str], None] = '842a42f73f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(), server_default='draft', nullable=False))
        batch_op.add_column(sa.Column('status_changed_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('status_notes', sa.Text(), nullable=True))
        batch_op.create_index('idx_features_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index('idx_features_status')
        batch_op.drop_column('status_notes')
        batch_op.drop_column('status_changed_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
