"""T1.1 lineage source-column parents

Revision ID: b4de1aac246b
Revises: affaec86825b
Create Date: 2026-05-06 08:15:49.397140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4de1aac246b'
down_revision: Union[str, Sequence[str], None] = 'affaec86825b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_lineage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_type', sa.Text(), server_default='feature', nullable=False))
        batch_op.add_column(sa.Column('parent_source_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_column', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('detected_method', sa.Text(), server_default='manual', nullable=False))
        batch_op.alter_column('parent_feature_id',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_feature_lineage_pair'), type_='unique')
        batch_op.create_unique_constraint('uq_feature_lineage_pair', ['child_feature_id', 'parent_type', 'parent_feature_id', 'parent_source_id', 'parent_column'])
        batch_op.create_index('idx_lineage_parent_source', ['parent_source_id'], unique=False)
        batch_op.create_foreign_key(None, 'data_sources', ['parent_source_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_lineage', schema=None) as batch_op:
        # Drop the auto-named FK on parent_source_id added in upgrade(); alembic
        # accepts None at runtime to mean "drop the single FK on this table",
        # but mypy's stubs require a name — silenced rather than guess at the
        # autogen-emitted suffix.
        batch_op.drop_constraint(None, type_='foreignkey')  # type: ignore[arg-type]
        batch_op.drop_index('idx_lineage_parent_source')
        batch_op.drop_constraint('uq_feature_lineage_pair', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_feature_lineage_pair'), ['child_feature_id', 'parent_feature_id'])
        batch_op.alter_column('parent_feature_id',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('detected_method')
        batch_op.drop_column('parent_column')
        batch_op.drop_column('parent_source_id')
        batch_op.drop_column('parent_type')

    # ### end Alembic commands ###
