"""initial schema

Revision ID: dbfa513c59ba
Revises: 
Create Date: 2026-05-06 05:01:43.307672

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dbfa513c59ba'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('storage_type', sa.Text(), server_default='local', nullable=False),
    sa.Column('format', sa.Text(), server_default='parquet', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('auto_refresh', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feature_groups',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('project', sa.Text(), server_default='', nullable=False),
    sa.Column('owner', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result_summary', sa.Text(), server_default='{}', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_schedules',
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('cron_expression', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_run_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('next_run_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('max_log_retention_days', sa.Integer(), server_default='30', nullable=False),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('features',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data_source_id', sa.Text(), nullable=False),
    sa.Column('column_name', sa.Text(), nullable=False),
    sa.Column('dtype', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('tags', sa.Text(), server_default='[]', nullable=False),
    sa.Column('owner', sa.Text(), server_default='', nullable=False),
    sa.Column('stats', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('definition_type', sa.Text(), nullable=True),
    sa.Column('definition_updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('generation_hints', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'column_name', name='uq_features_source_column')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index('idx_features_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_features_name', ['name'], unique=False)
        batch_op.create_index('idx_features_source', ['data_source_id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_by', sa.Text(), server_default='', nullable=False),
    sa.Column('applied_by', sa.Text(), server_default='', nullable=False),
    sa.Column('applied_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('change_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('context_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index('idx_action_items_feature', ['feature_id', 'status'], unique=False)
        batch_op.create_index('idx_action_items_status', ['status', 'created_at'], unique=False)

    op.create_table('feature_docs',
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), server_default='', nullable=False),
    sa.Column('long_description', sa.Text(), server_default='', nullable=False),
    sa.Column('expected_range', sa.Text(), server_default='', nullable=False),
    sa.Column('potential_issues', sa.Text(), server_default='', nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('model_used', sa.Text(), server_default='', nullable=False),
    sa.Column('hints_used', sa.Text(), nullable=True),
    sa.Column('context_features', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('feature_id', name='pk_feature_docs')
    )
    op.create_table('feature_group_members',
    sa.Column('group_id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['feature_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'feature_id', name='pk_feature_group_members')
    )
    with op.batch_alter_table('feature_group_members', schema=None) as batch_op:
        batch_op.create_index('idx_group_members_group_feature', ['group_id', 'feature_id'], unique=False)

    op.create_table('feature_lineage',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('child_feature_id', sa.Text(), nullable=False),
    sa.Column('parent_feature_id', sa.Text(), nullable=False),
    sa.Column('transform', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['child_feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_feature_id', 'parent_feature_id', name='uq_feature_lineage_pair')
    )
    with op.batch_alter_table('feature_lineage', schema=None) as batch_op:
        batch_op.create_index('idx_lineage_child', ['child_feature_id'], unique=False)
        batch_op.create_index('idx_lineage_parent', ['parent_feature_id'], unique=False)

    op.create_table('feature_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('changed_by', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('change_type', sa.Text(), server_default='metadata', nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id', 'version', name='uq_feature_versions_fid_ver')
    )
    op.create_table('monitoring_baselines',
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('baseline_stats', sa.Text(), server_default='{}', nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('feature_id', name='pk_monitoring_baselines')
    )
    op.create_table('monitoring_checks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('feature_name', sa.Text(), nullable=False),
    sa.Column('psi', sa.Float(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('llm_analysis_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_checks', schema=None) as batch_op:
        batch_op.create_index('idx_monitoring_checks_date', ['checked_at'], unique=False)
        batch_op.create_index('idx_monitoring_checks_feature', ['feature_name'], unique=False)

    op.create_table('usage_log',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('feature_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), server_default='', nullable=False),
    sa.Column('context', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.create_index('idx_usage_log_created', ['created_at'], unique=False)
        batch_op.create_index('idx_usage_log_feature', ['feature_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.drop_index('idx_usage_log_feature')
        batch_op.drop_index('idx_usage_log_created')

    op.drop_table('usage_log')
    with op.batch_alter_table('monitoring_checks', schema=None) as batch_op:
        batch_op.drop_index('idx_monitoring_checks_feature')
        batch_op.drop_index('idx_monitoring_checks_date')

    op.drop_table('monitoring_checks')
    op.drop_table('monitoring_baselines')
    op.drop_table('feature_versions')
    with op.batch_alter_table('feature_lineage', schema=None) as batch_op:
        batch_op.drop_index('idx_lineage_parent')
        batch_op.drop_index('idx_lineage_child')

    op.drop_table('feature_lineage')
    with op.batch_alter_table('feature_group_members', schema=None) as batch_op:
        batch_op.drop_index('idx_group_members_group_feature')

    op.drop_table('feature_group_members')
    op.drop_table('feature_docs')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index('idx_action_items_status')
        batch_op.drop_index('idx_action_items_feature')

    op.drop_table('action_items')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index('idx_features_source')
        batch_op.drop_index('idx_features_name')
        batch_op.drop_index('idx_features_created_at')

    op.drop_table('features')
    op.drop_table('job_schedules')
    op.drop_table('job_logs')
    op.drop_table('feature_groups')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
