"""T1.4a indexes: features(dtype) features(updated_at)

Revision ID: f871e02d23fb
Revises: affaec86825b
Create Date: 2026-05-06 07:39:00.480100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f871e02d23fb'
down_revision: Union[str, Sequence[str], None] = 'affaec86825b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index('idx_features_dtype', ['dtype'], unique=False)
        batch_op.create_index('idx_features_updated_at', ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index('idx_features_updated_at')
        batch_op.drop_index('idx_features_dtype')

    # ### end Alembic commands ###
