#!/usr/bin/env bash
# Spin up an isolated featcat sandbox.
#
# See deploy/sandbox/PLAN.md for the full design rationale. The TL;DR is:
#  - Clone the repo into /tmp/featcat-sandbox-<id>/repo (no shared .git)
#  - Generate a per-run .env layered on deploy/.env.example + chosen profile
#  - Auto-pick free ports starting at 8100 / 8180 / 5532
#  - docker compose -p featcat-sandbox-<id> with the sandbox override
#  - Wait for /api/health then print the URL + reset command
#
# Usage:
#   start-sandbox.sh --profile {local|lab} [--root /tmp] [--source /repo/path]
#                    [--no-wait]

set -euo pipefail
IFS=$'\n\t'

# shellcheck source=deploy/sandbox/scripts/lib/common.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly script_dir

# Defaults — overridable via flags or env vars.
profile=""
root_parent="/tmp"
source_repo=""
do_wait=true

usage() {
  cat <<'USAGE' >&2
Usage: start-sandbox.sh --profile {local|lab} [options]

Required:
  --profile {local|lab}   Host profile (selects build args + env defaults).

Optional:
  --root <path>           Parent directory for the sandbox root (default /tmp).
  --source <repo-path>    Source repo to clone (default: the repo containing
                          this script).
  --no-wait               Don't block on /api/health; return as soon as `up -d`
                          finishes.
  -h, --help              This message.

USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      profile="${2:-}"
      shift 2
      ;;
    --root)
      root_parent="${2:-}"
      shift 2
      ;;
    --source)
      source_repo="${2:-}"
      shift 2
      ;;
    --no-wait)
      do_wait=false
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      log_error "unknown flag: $1"
      usage
      exit 2
      ;;
  esac
done

if [[ -z "${profile}" ]]; then
  log_error "--profile is required (local or lab)"
  usage
  exit 2
fi

if [[ "${profile}" != "local" && "${profile}" != "lab" ]]; then
  log_error "--profile must be 'local' or 'lab', got: ${profile}"
  exit 2
fi

require_cmd docker "install Docker Engine"
require_cmd git "install git"
require_cmd curl "install curl"
require_cmd jq "install jq"
require_cmd ss "install iproute2"

# Resolve the source repo path. Default: the repo that contains this script.
if [[ -z "${source_repo}" ]]; then
  source_repo="$(cd "${script_dir}/../../.." && pwd)"
fi
if [[ ! -d "${source_repo}/.git" ]]; then
  log_error "source repo path is not a git checkout: ${source_repo}"
  exit 1
fi

# Verify the LLM model is present in the source repo. We never auto-download.
readonly model_file_name="gemma-4-E2B-it-Q4_K_M.gguf"
readonly source_model_path="${source_repo}/deploy/models/${model_file_name}"
if [[ ! -f "${source_model_path}" ]]; then
  log_error "LLM model not found at ${source_model_path}"
  log_error "fetch it once with:"
  log_error "  curl -L -o '${source_model_path}' 'https://huggingface.co/google/gemma-4-E2B-it-GGUF/resolve/main/${model_file_name}'"
  exit 1
fi

# Soft-warn if --profile local is chosen but a proxy is set in the calling env.
if [[ "${profile}" == "local" && -n "${HTTP_PROXY:-${http_proxy:-}}" ]]; then
  log_warn "--profile local but HTTP_PROXY is set in the shell; sandbox will run without proxy. Re-run with --profile lab if needed."
fi

# Allocate the sandbox id and root.
sandbox_id="$(timestamp_id)"
sandbox_root="${root_parent}/${sandbox_project_prefix}-${sandbox_id}"
project_name="${sandbox_project_prefix}-${sandbox_id}"

log_info "sandbox id      ${sandbox_id}"
log_info "sandbox root    ${sandbox_root}"
log_info "compose project ${project_name}"
log_info "source repo     ${source_repo}"
log_info "profile         ${profile}"

# Tear down hint on any failure from here on.
_emit_teardown_hint() {
  log_error "teardown hint: bash ${script_dir}/reset-sandbox.sh --id ${sandbox_id}"
}
trap _emit_teardown_hint ERR

# Pick free host ports.
featcat_port="$(pick_free_port "${sandbox_default_featcat_port}")"
llm_port="$(pick_free_port "${sandbox_default_llm_port}")"
pg_port="$(pick_free_port "${sandbox_default_pg_port}")"
log_info "ports           featcat=${featcat_port} llm=${llm_port} pg=${pg_port}"

# Create the root and clone the repo.
mkdir -p "${sandbox_root}"
git clone --local --quiet "${source_repo}" "${sandbox_root}/repo"
log_ok "cloned ${source_repo} into ${sandbox_root}/repo"

# Record the compose project name so reset-sandbox.sh can find it later.
printf '%s\n' "${project_name}" > "${sandbox_root}/compose-project-name"

# Build the layered .env: deploy/.env.example → profile.env → runtime overrides.
sandbox_env="${sandbox_root}/.env"
profile_env="${script_dir}/../compose/${profile}.env"
{
  printf '# Generated by start-sandbox.sh on %s\n' "$(date -u +%FT%TZ)"
  printf '# Layer 1: deploy/.env.example\n'
  cat "${source_repo}/deploy/.env.example"
  printf '\n# Layer 2: %s\n' "${profile_env}"
  cat "${profile_env}"
  printf '\n# Layer 3: runtime overrides\n'
  printf 'FEATCAT_PORT=%s\n' "${featcat_port}"
  printf 'SANDBOX_LLM_PORT=%s\n' "${llm_port}"
  printf 'SANDBOX_PG_PORT=%s\n' "${pg_port}"
  printf 'SANDBOX_MODEL_DIR=%s\n' "${source_repo}/deploy/models"
  printf 'DATA_DIR=%s\n' "${sandbox_root}/data"
} > "${sandbox_env}"
log_ok "wrote ${sandbox_env}"

# Pre-seed the sandbox data directory with the synthetic fixture.
mkdir -p "${sandbox_root}/data"
cp "${script_dir}/../fixtures/synthetic.parquet" "${sandbox_root}/data/"
log_ok "seeded ${sandbox_root}/data with the synthetic fixture"

# Source the profile env so SANDBOX_BUILD_NETWORK and friends are visible to
# our bash logic. We use `set -a` so every var becomes exported automatically.
set -a
# shellcheck source=/dev/null
. "${profile_env}"
set +a

# Compose file paths inside the clone.
base_compose="${sandbox_root}/repo/deploy/docker-compose.yml"
override_compose="${sandbox_root}/repo/deploy/sandbox/compose/docker-compose.sandbox.yml"

compose_args_array "${project_name}" "${base_compose}" "${override_compose}" "${sandbox_env}"

# Build.
build_args=()
if [[ -n "${SANDBOX_BUILD_NETWORK:-}" ]]; then
  build_args+=(--build-arg "BUILDKIT_INLINE_CACHE=1")
fi
build_cmd=(docker compose "${_compose_args[@]}" build "${build_args[@]}")
log_info "running: ${build_cmd[*]}"
if [[ -n "${SANDBOX_BUILD_NETWORK:-}" ]]; then
  # `compose build` itself doesn't accept --network, but it honours
  # DOCKER_BUILDKIT_NETWORK_HOST for the underlying buildkit invocation. The
  # safer approach on lab boxes is to pre-build with `docker build --network=host`
  # and let compose reuse the cached image; we surface a clear message instead
  # of silently doing the wrong thing.
  log_warn "lab profile: ensure images are pre-built with --network=host if BuildKit cannot reach the proxy"
fi
"${build_cmd[@]}"
log_ok "build complete"

# Up.
up_cmd=(docker compose "${_compose_args[@]}" up -d)
log_info "running: ${up_cmd[*]}"
"${up_cmd[@]}"
log_ok "containers started"

if ! ${do_wait}; then
  log_warn "--no-wait set; skipping the /api/health probe"
  trap - ERR
  exit 0
fi

# Wait for /api/health to report status=ok. Timeout 90 s.
health_url="http://localhost:${featcat_port}/api/health"
log_info "waiting on ${health_url}"
deadline=$(( $(date +%s) + 90 ))
attempts=0
while true; do
  attempts=$((attempts + 1))
  if response="$(curl -fsS --max-time 3 "${health_url}" 2>/dev/null)"; then
    if printf '%s' "${response}" | jq -e '.status == "ok"' >/dev/null 2>&1; then
      log_ok "/api/health is ok after ${attempts} attempts"
      break
    fi
  fi
  if (( $(date +%s) >= deadline )); then
    log_error "/api/health never returned status=ok within 90s"
    log_error "last response: ${response:-<no response>}"
    exit 1
  fi
  sleep 2
done

# All good — disable the teardown hint so the success summary stands alone.
trap - ERR

cat <<SUMMARY

${_c_ok}Sandbox ready${_c_reset}

  Web UI / API   : http://localhost:${featcat_port}
  llama.cpp     : http://localhost:${llm_port}
  Postgres      : localhost:${pg_port}  (user/db: featcat / featcat)
  Compose proj  : ${project_name}
  Sandbox root  : ${sandbox_root}

  Run a CLI cmd : bash ${script_dir}/exec-sandbox.sh --id ${sandbox_id} -- featcat doctor
  Open shell    : bash ${script_dir}/exec-sandbox.sh --id ${sandbox_id} -- bash
  Tear down     : bash ${script_dir}/reset-sandbox.sh --id ${sandbox_id}

SUMMARY
